name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image Test
        run: docker build -t django:test .

      - name: Django Container Test
        run: |
          docker run --name django-container django:test pytest --cov --cov-report=xml
          docker cp django-container:/okpos/coverage.xml ${{ github.workspace }}/coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
